'use strict';
const $=id=>document.getElementById(id), KEY='strongest-name-v1';
const headers=['タイムスタンプ','discord ID','新商品の名前','新商品のジャンル','新商品の説明'];
function fresh(name='新しい大会'){return {id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,name,limit:3,url:'',gid:'',headers:[...headers],rows:[],idCol:1,nameCol:2,categoryCol:3,fields:[4],format:{heading:'{大会名}',category:true,labels:false,code:true,number:true},updated:''};}
let state={version:1,active:'',tournaments:[]};
function valid(s){return s?.version===1&&Array.isArray(s.tournaments)&&s.tournaments.length>0&&new Set(s.tournaments.map(t=>t.id)).size===s.tournaments.length&&s.tournaments.every(t=>typeof t.id==='string'&&typeof t.name==='string'&&t.name.length<=150&&Number.isInteger(t.limit)&&t.limit>=0&&t.limit<=100000&&typeof t.url==='string'&&typeof t.gid==='string'&&Array.isArray(t.headers)&&t.headers.length>1&&t.headers.every(h=>typeof h==='string')&&Array.isArray(t.rows)&&t.rows.every(r=>Array.isArray(r)&&r.length===t.headers.length&&r.every(c=>typeof c==='string'))&&[t.idCol,t.nameCol].every(c=>Number.isInteger(c)&&c>=0&&c<t.headers.length)&&Number.isInteger(t.categoryCol)&&t.categoryCol>=-1&&t.categoryCol<t.headers.length&&Array.isArray(t.fields)&&t.fields.every(c=>Number.isInteger(c)&&c>=0&&c<t.headers.length)&&typeof t.format?.heading==='string'&&t.format.heading.length<=200&&['category','labels','code','number'].every(k=>typeof t.format[k]==='boolean'));}
function notice(s){$('notice').textContent=s;}
try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(!valid(s))throw Error();state=s;}}catch{notice('保存データを読み込めませんでした。バックアップから復元できます。');}
if(!state.tournaments.length)state.tournaments=[fresh()];if(!state.tournaments.some(t=>t.id===state.active))state.active=state.tournaments[0].id;
const current=()=>state.tournaments.find(t=>t.id===state.active);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{notice('ブラウザへの保存に失敗しました。今すぐ全大会をバックアップしてください。');}}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function nav(){const n=$('tournaments');n.replaceChildren();for(const t of state.tournaments){const b=el('button',t.name,t.id===state.active?'selected':'');b.onclick=()=>{state.active=t.id;save();render();};n.append(b);}}
function render(){const t=current();nav();for(const k of ['name','limit','url','gid'])$(k).value=t[k];$('heading').value=t.format.heading;for(const k of ['category','labels','code','number'])$(k).checked=t.format[k];
 for(const k of ['idCol','nameCol','categoryCol']){const s=$(k);s.replaceChildren();if(k==='categoryCol')s.add(new Option('なし','-1'));t.headers.forEach((h,i)=>s.add(new Option(`${i+1}: ${h}`,i)));s.value=t[k];}
 $('fields').replaceChildren();t.headers.forEach((h,i)=>{if(i===t.nameCol)return;const l=el('label'),c=el('input');c.type='checkbox';c.checked=t.fields.includes(i);c.onchange=()=>{t.fields=c.checked?[...t.fields,i].sort((a,b)=>a-b):t.fields.filter(x=>x!==i);save();results();};l.append(c,document.createTextNode(' '+h));$('fields').append(l);});$('updated').textContent=t.updated?`最終読込：${t.updated}`:'まだ回答を読み込んでいません。';results();}
function table(container,hs,rs){const tb=el('table'),head=el('thead'),hr=el('tr');hs.forEach(h=>hr.append(el('th',h)));head.append(hr);tb.append(head);const body=el('tbody');rs.forEach(r=>{const tr=el('tr');r.forEach(c=>tr.append(el('td',c)));body.append(tr);});tb.append(body);container.replaceChildren(tb);}
function results(){const t=current(),rows=Core.assess(t);$('stats').replaceChildren();for(const [label,n] of [['回答総数',rows.length],['採用',rows.filter(r=>r.status==='採用').length],['上限超過',rows.filter(r=>r.status==='上限超過').length],['入力不備',rows.filter(r=>r.status.endsWith('未入力')).length]]){const box=el('div',undefined,'stat');box.append(el('strong',n),el('span',label));$('stats').append(box);}
 const byID=new Map();for(const r of rows){const key=r.id||'（ID未入力）';if(!byID.has(key))byID.set(key,[0,0,0]);const c=byID.get(key);c[0]++;if(r.status==='採用')c[1]++;if(r.status==='上限超過')c[2]++;}table($('counts'),['Discord ID','全回答','採用','超過'],[...byID].map(([id,c])=>[id,...c]));
 const shown=rows.filter(r=>!$('filter').value||r.status===$('filter').value);table($('answers'),['元の行','判定',...t.headers],shown.map(r=>[r.row,r.status,...r.cells]));
 $('output').replaceChildren();let messages;try{messages=Core.output(t);}catch(e){$('output').append(el('p',e.message));return;}if(!messages.length)$('output').append(el('p','採用できる回答がまだありません。','muted'));messages.forEach((s,i)=>{const div=el('div'),bar=el('div',undefined,'bar'),b=el('button','コピー');bar.append(el('span',`メッセージ ${i+1} / ${messages.length} · ${s.length}文字`),b);const ta=el('textarea');ta.value=s;ta.readOnly=true;ta.setAttribute('aria-label',`Discord出力 ${i+1}`);b.onclick=async()=>{try{await navigator.clipboard.writeText(s);b.textContent='コピーしました';}catch{ta.focus();ta.select();notice('出力欄を選択しました。コピー操作を行ってください。');}};div.append(bar,ta);$('output').append(div);});}
$('new').onclick=()=>{const name=prompt('大会名を入力してください');if(!name?.trim())return;const t=fresh(name.trim().slice(0,150));state.tournaments.push(t);state.active=t.id;save();render();};
$('delete').onclick=()=>{if(!confirm(`「${current().name}」と回答データを削除しますか？`))return;state.tournaments=state.tournaments.filter(t=>t.id!==state.active);if(!state.tournaments.length)state.tournaments.push(fresh());state.active=state.tournaments[0].id;save();render();};
for(const k of ['name','limit','url','gid'])$(k).onchange=()=>{const t=current();if(k==='limit'){const v=Number($(k).value);if(!Number.isInteger(v)||v<0||v>100000){notice('上限は0〜100000の整数で指定してください。');$(k).value=t.limit;return;}t.limit=v;}else t[k]=$(k).value.trim();if(!t.name)t.name='名称未設定';save();nav();results();};
for(const k of ['idCol','nameCol','categoryCol'])$(k).onchange=()=>{current()[k]=Number($(k).value);save();render();};
$('heading').oninput=()=>{current().format.heading=$('heading').value;save();results();};for(const k of ['category','labels','code','number'])$(k).onchange=()=>{current().format[k]=$(k).checked;save();results();};$('filter').onchange=results;
function ingest(text,t){const data=Core.parseCSV(text);const old=t.headers;const find=(index,re,fallback)=>{const same=data.headers.indexOf(old[index]);return same>=0?same:Math.max(fallback,data.headers.findIndex(h=>re.test(h)));};const idCol=find(t.idCol,/discord.*id|ディスコード/i,0),nameCol=find(t.nameCol,/名前|名称/,0),categoryCol=find(t.categoryCol,/ジャンル|カテゴリ/,-1);const fields=t.fields.map(i=>data.headers.indexOf(old[i])).filter(i=>i>=0);Object.assign(t,data,{idCol,nameCol,categoryCol,fields,updated:new Date().toLocaleString('ja-JP')});save();render();notice(`${t.name}：${data.rows.length}件を読み込みました。列の対応を確認してください。`);}
$('csv').onchange=async e=>{const t=current(),f=e.target.files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('CSVは10MB以内で読み込んでください。');ingest(await f.text(),t);}catch(err){notice(err.message);}e.target.value='';};
$('fetch').onclick=async()=>{const t=current();t.url=$('url').value.trim();t.gid=$('gid').value.trim();save();const b=$('fetch');b.disabled=true;try{const res=await fetch(Core.sheetURL(t.url,t.gid),{credentials:'omit',signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error(`HTTP ${res.status}`);const text=await res.text();if(text.length>10*1024*1024)throw Error('10MBを超えています');ingest(text,t);}catch(e){notice(`URLから取得できませんでした（${e.message}）。公開範囲とgidを確認するか、Google SheetsからCSVをダウンロードして読み込んでください。既存の回答は保持しています。`);}finally{b.disabled=false;}};
$('demo').onclick=()=>{const t=current();if(t.rows.length&&!confirm('現在の回答を架空のデモ回答に置き換えますか？'))return;ingest('タイムスタンプ,discord ID,新商品の名前,新商品のジャンル,新商品の説明\n2026/09/13 10:00:00,demo_user,銀河パン,食品,星の形をした架空のパン\n2026/09/13 10:01:00,demo_user,流星ソーダ,飲料,"架空の炭酸飲料\nきらめくラベル"\n2026/09/13 10:02:00,demo_user,月面プリン,食品,月の形のプリン\n2026/09/13 10:03:00,demo_user,太陽ゼリー,食品,4件目は初期上限を超過\n2026/09/13 10:04:00,,名無し飴,食品,ID未入力の例',t);};
$('backup').onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`tournaments-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw Error('バックアップは20MB以内にしてください。');const s=JSON.parse(await f.text());if(!valid(s))throw Error('このツールの有効なバックアップではありません。');if(!confirm('全大会をバックアップの内容に置き換えますか？'))return;state=s;if(!state.tournaments.some(t=>t.id===state.active))state.active=state.tournaments[0].id;save();render();notice('バックアップを復元しました。');}catch(err){notice(err.message);}finally{e.target.value='';}};
render();
