'use strict';
(function(){
 let lastId=null,selectedRound=0,exportUrls=[],renderedBracket=null,exportToken=0;
 function settings(t){if(!t.bracketSetup||typeof t.bracketSetup!=='object'||Array.isArray(t.bracketSetup))t.bracketSetup={};const s=t.bracketSetup;
 if(!['answers','manual','demo'].includes(s.source))s.source='answers';if(typeof s.manual!=='string')s.manual='';if(!Number.isInteger(s.demoCount)||s.demoCount<2||s.demoCount>256)s.demoCount=16;if(!Number.isInteger(s.k)||s.k<2||s.k>10)s.k=2;if(typeof s.randomize!=='boolean')s.randomize=true;if(!Array.isArray(s.selected)||!s.selected.every(x=>typeof x==='string'))s.selected=null;return s;}
 function sourceEntries(t){const s=settings(t);if(s.source==='demo')return Bracket.demo(s.demoCount);if(s.source==='manual')return s.manual.split(/\r?\n/).map((name,i)=>({id:`manual-${i+1}`,name:name.trim(),details:'',row:i+1})).filter(e=>e.name);
 return Core.assess(t).filter(r=>r.status==='採用').map(r=>({id:`row-${r.row}`,name:r.cells[t.nameCol],details:[...new Set([...(t.extraCols||[]),...t.fields])].filter(i=>i>=0&&i!==t.nameCol&&r.cells[i]).map(i=>`${t.headers[i]}：${r.cells[i]}`).join('\n'),row:r.row}));}
 function selectedEntries(t){const pool=sourceEntries(t),s=settings(t);return s.source==='answers'&&s.selected!==null?pool.filter(e=>s.selected.includes(e.id)):pool;}
 function cleanExports(){exportToken++;for(const url of exportUrls)URL.revokeObjectURL(url);exportUrls=[];$('exportPreview').replaceChildren();}
 function tab(bracket){$('collectionPanel').hidden=bracket;$('bracketPanel').hidden=!bracket;$('showBracket').classList.toggle('selected',bracket);$('showCollection').classList.toggle('selected',!bracket);if(bracket)render(current());}
 $('showCollection').onclick=()=>tab(false);$('showBracket').onclick=()=>tab(true);
 function renderSetup(t){const s=settings(t);$('entrySource').value=s.source;$('manualEntries').value=s.manual;$('bracketDemoCount').value=s.demoCount;$('randomizeEntries').checked=s.randomize;$('manualEntriesLabel').hidden=s.source!=='manual';$('demoCountLabel').hidden=s.source!=='demo';$('entrySelection').hidden=s.source!=='answers';
 const pool=sourceEntries(t),chosen=selectedEntries(t);$('entrySummary').textContent=`参加予定 ${chosen.length} / 256件${s.source==='answers'?`（採用回答 ${pool.length}件）`:''}${chosen.length<2?' — 2件以上必要です。':chosen.length>256?' — 256件以下に絞ってください。':''}`;
 $('entryList').replaceChildren();if(s.source==='answers')for(const e of pool){const l=el('label'),c=el('input');c.type='checkbox';c.checked=s.selected===null||s.selected.includes(e.id);c.onchange=()=>{if(s.selected===null)s.selected=pool.map(e=>e.id);s.selected=c.checked?[...new Set([...s.selected,e.id])]:s.selected.filter(id=>id!==e.id);save();renderSetup(t);};l.append(c,document.createTextNode(`行${e.row} · ${e.name}`));$('entryList').append(l);}
 const host=$('bracketProposals');host.replaceChildren();$('buildBracket').disabled=chosen.length<2||chosen.length>256;
 if(chosen.length<2||chosen.length>256){host.append(el('p','参加件数が2〜256件になると、2〜10人戦の構成案を表示します。','muted'));return;}
 const table=el('table'),head=el('tr');['1戦の最大人数','ラウンド','試合数','初戦シード','各ラウンドの構成','選択'].forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');
 for(const p of Bracket.proposals(chosen.length)){const row=el('tr',undefined,s.k===p.k?'proposal-picked':'');[`${p.k}人`,p.rounds,p.matches,p.byes,p.sizes.map((v,i)=>`R${i+1}: ${v}`).join('\n')].forEach(x=>row.append(el('td',x)));const td=el('td'),b=el('button',s.k===p.k?'選択中':'この構成');b.setAttribute('aria-label',`${p.k}人戦を選択`);b.onclick=()=>{s.k=p.k;save();renderSetup(t);};td.append(b);row.append(td);body.append(row);}table.append(body);host.append(table);$('buildBracket').textContent=`最大${s.k}人戦でトーナメントを作成`;
 }
 function renderDiagram(t){if(!t.bracket||!$('diagramDetails').open)return;const art=BracketImage.diagram(t.bracket,t.name);$('bracketDiagram').innerHTML=art.svg;}
 function renderMatches(t){const b=t.bracket,g=Bracket.graph(b.entries,b.k),st=Bracket.status(b,g),entries=new Map(b.entries.map(e=>[e.id,e]));selectedRound=Math.min(Math.max(0,selectedRound),g.rounds.length-1);
 $('roundTabs').replaceChildren();g.rounds.forEach((round,i)=>{const done=round.filter(m=>st.states.get(m.id).winner).length,button=el('button',`${i===g.rounds.length-1?'決勝':`R${i+1}`} (${done}/${round.length})`,i===selectedRound?'selected':'');button.onclick=()=>{selectedRound=i;cleanExports();renderMatches(t);};$('roundTabs').append(button);});
 $('matchCards').replaceChildren();for(const m of g.rounds[selectedRound]){const ms=st.states.get(m.id),card=el('article',undefined,'match-card');card.append(el('h4',`${m.id} · ${m.sources.length}人戦`));card.append(el('span',ms.winner?'勝者確定':ms.ready?'勝者を選択':'前の対戦の結果待ち','muted'));
 m.sources.forEach((src,i)=>{const id=ms.slots[i],entry=id?entries.get(id):null,button=el('button',entry?`${ms.winner===id?'✓ ':''}${entry.name}`:`${src.id} の勝者（未確定）`,'contender'+(ms.winner===id?' winner':''));button.disabled=!ms.ready;button.setAttribute('aria-pressed',String(ms.winner===id));button.onclick=()=>{if(ms.winner===id)return;const affected=Bracket.descendants(g,m.id).filter(id=>b.results[id]);if(affected.length&&!confirm(`勝者を変更すると、関連する上位${affected.length}試合の結果を解除します。変更しますか？`))return;Bracket.choose(b,m.id,id);save();cleanExports();renderLive(t);};card.append(button);
 if(entry){const detail=el('details'),summary=el('summary',`回答詳細${entry.row?` · 元の行${entry.row}`:''}`);detail.append(summary,el('pre',entry.name+(entry.details?'\n\n'+entry.details:'')));card.append(detail);}});
 if(ms.winner){const reset=el('button','この対戦の結果を取り消す');reset.onclick=()=>{if(!confirm('この対戦と、関連する上位対戦の結果を取り消しますか？'))return;Bracket.choose(b,m.id,null);save();cleanExports();renderLive(t);};card.append(reset);}
 const parent=g.matches.find(other=>other.sources.some(src=>src.type==='match'&&src.id===m.id));card.append(el('div',parent?`勝者 → ${parent.id}`:'勝者 → 優勝','destination'));$('matchCards').append(card);}
 }
 function renderLive(t){const b=t.bracket;$('bracketLive').hidden=!b;if(!b)return;const g=Bracket.graph(b.entries,b.k),st=Bracket.status(b,g);$('bracketSummary').replaceChildren();for(const [label,value] of [['参加回答',b.entries.length],['確定した試合',`${st.completed} / ${g.matches.length}`],['初戦シード',g.byes.length]]){const box=el('div',undefined,'stat');box.append(el('strong',value),el('span',label));$('bracketSummary').append(box);}
 let stale=false;if(b.source==='answers'){const pool=Core.assess(t).filter(r=>r.status==='採用').map(r=>({id:`row-${r.row}`,name:r.cells[t.nameCol],details:[...new Set([...(t.extraCols||[]),...t.fields])].filter(i=>i>=0&&i!==t.nameCol&&r.cells[i]).map(i=>`${t.headers[i]}：${r.cells[i]}`).join('\n'),row:r.row}));stale=JSON.stringify(pool)!==b.signature;}
 $('bracketStale').textContent=(b.source==='demo'?'仮データのトーナメントです。 ':'')+(stale?'収集データまたは列設定が作成時から変わっています。進行中の表は作成時の回答を保持しています。':'参加回答は作成時点の内容で固定しています。');$('bracketChampion').hidden=!st.champion;$('bracketChampion').textContent=st.champion?`優勝：${b.entries.find(e=>e.id===st.champion).name}`:'';renderMatches(t);renderDiagram(t);}
 function render(t){if(lastId!==t.id){lastId=t.id;selectedRound=0;renderedBracket=null;cleanExports();$('bracketSetup').open=!t.bracket;$('bracketDiagram').replaceChildren();}if(renderedBracket!==JSON.stringify([t.name,t.bracket])){renderedBracket=JSON.stringify([t.name,t.bracket]);cleanExports();}renderSetup(t);renderLive(t);}
 $('entrySource').onchange=()=>{settings(current()).source=$('entrySource').value;save();renderSetup(current());};
 $('manualEntries').onchange=()=>{settings(current()).manual=$('manualEntries').value;save();renderSetup(current());};
 $('bracketDemoCount').onchange=()=>{const n=Number($('bracketDemoCount').value);if(!Number.isInteger(n)||n<2||n>256){notice('仮データは2〜256件で指定してください。');$('bracketDemoCount').value=settings(current()).demoCount;return;}settings(current()).demoCount=n;save();renderSetup(current());};
 $('randomizeEntries').onchange=()=>{settings(current()).randomize=$('randomizeEntries').checked;save();};
 $('selectAllEntries').onclick=()=>{settings(current()).selected=null;save();renderSetup(current());};$('selectFirstEntries').onclick=()=>{settings(current()).selected=sourceEntries(current()).slice(0,256).map(e=>e.id);save();renderSetup(current());};$('selectNoEntries').onclick=()=>{settings(current()).selected=[];save();renderSetup(current());};
 $('buildBracket').onclick=()=>{const t=current(),s=settings(t);try{let entries=selectedEntries(t);if(t.bracket&&!confirm('現在のトーナメントと勝敗を、新しい組み合わせに置き換えますか？'))return;if(s.randomize)entries=Bracket.shuffle(entries,Bracket.secureRandom);t.bracket=Bracket.create(entries,s.k,s.source,JSON.stringify(sourceEntries(t)));save();selectedRound=0;cleanExports();$('bracketSetup').open=false;render(t);notice('トーナメントを作成しました。各対戦の勝者を選んでください。');$('bracketLive').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){notice(e.message);}};
 $('reshuffleBracket').onclick=()=>{const t=current(),b=t.bracket;if(!b||!confirm('参加回答を再抽選し、すべての勝敗をリセットしますか？'))return;t.bracket=Bracket.create(Bracket.shuffle(b.entries,Bracket.secureRandom),b.k,b.source,b.signature);save();selectedRound=0;cleanExports();render(t);};
 $('resetResults').onclick=()=>{const t=current();if(!t.bracket||!confirm('組み合わせを維持し、すべての勝敗をリセットしますか？'))return;t.bracket.results={};save();cleanExports();renderLive(t);};
 $('diagramDetails').ontoggle=()=>renderDiagram(current());
 for(const id of ['imageMode','imageScope','imageSpoiler'])$(id).onchange=cleanExports;
 $('exportBracket').onclick=async()=>{const t=current();if(!t.bracket)return;cleanExports();const token=exportToken,b=t.bracket,mode=$('imageMode').value,scope=$('imageScope').value,spoiler=$('imageSpoiler').checked,button=$('exportBracket');button.disabled=true;button.textContent='画像を生成中…';try{
 const arts=scope==='all'?[BracketImage.diagram(b,t.name,mode)]:BracketImage.roundPages(b,t.name,selectedRound,mode);
 for(let i=0;i<arts.length;i++){const blob=await BracketImage.png(arts[i]);if(token!==exportToken)break;const filename=`${spoiler?'SPOILER_':''}tournament-${mode}-${scope==='all'?'all':`round${selectedRound+1}`}-${i+1}.png`,url=URL.createObjectURL(blob);exportUrls.push(url);const box=el('div',undefined,'export-card'),img=el('img');img.src=url;img.alt=`トーナメント画像 ${i+1}`;const bar=el('div',undefined,'bar'),download=el('a',`PNGを保存（${i+1}/${arts.length}）`);download.href=url;download.download=filename;bar.append(download);const file=new File([blob],filename,{type:'image/png'});if(navigator.canShare?.({files:[file]})){const share=el('button','共有する');share.onclick=async()=>{try{await navigator.share({files:[file]});}catch(e){if(e.name!=='AbortError')notice('共有できませんでした。PNGを保存して添付してください。');}};bar.append(share);}box.append(img,bar,el('small',filename));$('exportPreview').append(box);}
 }catch(e){notice(`画像生成に失敗しました：${e.message}`);}finally{button.disabled=false;button.textContent='画像を生成';}};
 globalThis.TournamentUI={render};render(current());
})();
